apiVersion: v1
kind: Service
metadata:
  name: {{ include "aseit-api-helm.fullname" . }}
  labels:
{{ include "aseit-api-helm.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8091
      nodePort: 32656
  selector:
    app.kubernetes.io/name: {{ include "aseit-api-helm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
